* Animando escenas con python

Expresar conceptos matem치ticos a otras personas no es f치cil ya que debes:

+ Entender el concepto.
+ Comunicar de manera efectiva el concepto.
+ Crear un espacio en el que la otra persona pueda visualizar la informaci칩n de
  tal manera que pueda ser entendida de manera efectiva.

Por esta raz칩n presentaremos una herramienta de animaci칩n para la ense침anza de
las matem치ticas, dicha herramienta es una biblioteca de Python llamada =manim=,
esta es la herramienta de visualizaci칩n utilizada por el canal de youtube
llamado [[https://www.youtube.com/@3blue1brown][3blue1brown]] (si no lo conoces, deber칤as). Lo primero que necesitamos
antes de utilizar la herramienta es instalar las dependencias y la herramienta
en s칤, para ello es necesario conocer la [[https://docs.manim.community/en/stable/index.html][p치gina oficial del proyecto]] donde se
encontrar치 toda la documentaci칩n necesaria (as칤 como las instrucciones de
instalaci칩n). Por cuestiones de tiempo s칩lo se pondr치n las instrucciones de
instalaci칩n para sistemas linux (basados en Debian), la instalaci칩n para [[MacOs][macos]] y
[[https://docs.manim.community/en/stable/installation/windows.html][windows]] puede ser seguida desde la [[https://docs.manim.community/en/stable/installation/linux.html][p치gina oficial]].

** Instrucciones de instalaci칩n (Linux)

Lo primero que tenemos que hacer es instalar un par de bibliotecas y la
aplicaci칩n =ffmpeg= que se encargar치 de generar el v칤deo:

#+begin_src bash
  sudo apt update
  sudo apt install build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg texlive texlive-latex-extra
#+end_src

Otro requerimento es tener instalado =python3-pip= y =venv= y =pkgconfig=:

#+begin_src bash
  sudo apt install python3-pip python3-venv python3-dev pkg-config
#+end_src

Por 칰ltimo se instala =manim= con:

#+begin_src bash
  pip3 install manim
#+end_src

Esto instala =manim= de manera global, como python es una herramienta que es
utilizada por varios administradores de paquetes (como =Conda=) lo m치s
recomendable es crear un =ambiente virtual= al iniciar con un proyecto nuevo, de
esta manera las dependencias del proyecto son locales al proyecto (es decir, no
se comparten de manera global en toda la computadora) ya que en ocasiones pueden
ocurrir "colisiones" de dependencias donde el proyecto A requiere la version =x=
de una biblioteca mientras que el proyecto B requiere la versi칩n =y= de la misma
biblioteca. Lo mejor de esto es que los ambientes virtuales funcionan en
cualquier sistema operativo.

** Ambientes virtuales en python

Podemos ver un ambiente virtual como una cajita que almacena todos los juguetes
de la sesi칩n de juego, de esta manera podemos mantener organizado nuestro
espacio de trabajo sin los dolores de cabeza que conlleva administrar de manera
general todas las dependencias que los proyectos de python requieren. Para
generar un ambiente virtual basta con ejecutar el siguiente comando:

#+begin_src bash
  mkdir mi_proyecto                # Creamos una carpeta para asociarla al proyecto
  cd mi_proyecto                   # Ingresamos al proyecto
  python3 -m venv .mi_proyecto     # Creamos un ambiente virtual
  source .mi_proyecto/bin/activate # Activamos el amiente virtual
  pip install --upgrade pip        # Refrescamos la versi칩n del administrador de paquetes
  pip install mis_bibliotecas      # Instalamos las dependencias
#+end_src

Para nuestra sesi칩n de animaci칩n crearemos un proyecto llamado =pixar101= de la
siguiente forma:

#+begin_src bash
  mkdir pixar
  cd pixar
  python3 -m venv .pixar
  source .pixar/bin/activate
  pip install --upgrade pip
  pip install manim
#+end_src

** 춰Hola Mundo!

Los ejemplos de este documento fueron sacados del [[https://docs.manim.community/en/stable/tutorials/quickstart.html][tutorial oficial de manim]]

Para comenzar crearemos un archivo llamado =hola_mundo.py= donde vamos a animar
algo muy sencillo, para =manim= una animaci칩n sucede en el contexto de una escena
(como en el cine), las escenas heredan de la clase =Scene=:

#+begin_src python
  class HolaMundo(Scene):
      def construct(self)
      # Ac치 van las instrucciones de la animaci칩n
#+end_src

Recuerden que en python los constructores de las clases se definen a trav칠s de
una funci칩n llamada =construct=, dentro de este constructor podemos hacer uso de
objetos como ejes, seguidores de posici칩n/movimiento, animar puntos, etc.

Para ejecutar nuestra animaci칩n necesitamos correrla con el siguiente comando:

#+begin_src bash
  manim hola_mundo.py
#+end_src

Durante este tutorial estaremos siguiendo los ejemplos m치s sencillos que se
muestran en la [[https://docs.manim.community/en/stable/examples.html][gu칤a oficial de manim]]

*** Calentando motores

La animaci칩n m치s simple que podemos generar es una imagen est치tica (游뗻),
dibujaremos figuras b치sicas como un cuadrado, un tri치ngulo, un c칤rculo y una
letra, agregaremos color a dichas figuras y sobrepondremos las im치genes para
hacerlo m치s interesante.

La primer cosa que tenemos que hacer dentro de nuestro script es importar la
biblioteca de animaci칩n, para ello necesitamos insertar lo siguiente:

#+begin_src python
  from manim import *
#+end_src

Despu칠s es necesario declarar el color de fondo que v치mos a estar utilizando, el
color se define utilizando un formato hexadecimal (los c칩digos de los colores
pueden ser consultados en esta [[https://htmlcolorcodes.com/][p치gina]]), para acceder a la c치mara hacemos
referencia al objeto =self.camera=, dicho objeto tiene hartos atributos y uno de
ellos es =background_color=, entonces para establecer el gris de "fondo" escribimos:

#+begin_src python
  self.background_color = "#ece6e2"
#+end_src

Ahora definiremos un par de colores, los colores son simplemente cadenas de
texto con el sufijo =#=:

#+begin_src python
  verde = "#87c2a5"
  azul  = "#525893"
  rojo  = "#e07a5f"
  negro = "#343434" # Los dise침adores dicen que es "malo" usar el negro puro
#+end_src

Crear figuras es relativamente f치cil, para generar un c칤rculo usamos =Circle=,
para generar un tr칤angulo usamos =Triangle= y para generar un cuadrado usamos
=Square=:

#+begin_src python
  circulo = Circle(color=azul, fill_opacity=1).shift(LEFT)
  cuadrado = Square(color=rojo, fill_opacity=1).shift(UP)
  triangulo = Triangle(color=verde, fill_opacity=1).shift(RIGHT)
#+end_src

쯈u칠 es ese =.shift(ALGO)= que pones al final de declarar cada figura? Bien, por
defecto =manim= dibuja todo lo que le digamos en el centro de la pantalla, para
evitar que todo se vea encimado movemos (=shift=) cada figura hacia arriba (=UP=), a
la derecha (=RIGHT=) o a la izquierda (=LEFT=).

Para dibujar las figuras debemos mandar a llamar al m칠todo =self.add= seguido de
una tupla donde le decimos a =manim= qu칠 es lo que queremos dibujar:

#+begin_src python
  self.add(circulo, cuadrado, triangulo) # El orden de las variables importa!!!
#+end_src

=manim= soporta el uso de LaTeX, probemos agregar texto a nuestra escena:

#+begin_src python
  letra = MathTex(r"\mathbb{J}", fill_color=logo_black).scale(6)
  letra.shift(3 * LEFT + 1.5 * UP)
#+end_src

Para renderizar latex hacemos una llamada a =MathTex= dentro de la llamada podemos
poner cualquier cadena de texto para rederizado, por 칰ltimo escalamos la letra 6
veces (=.scale=), despu칠s de definir la letra la movemos 3 unidades a la izquieda
y 1.5 hacia arriba 쮸lguien identific칩 una transformacion lineal 游뱂?

Despu칠s de definir m칰ltiples elementos es posible agruparlos para "imprimirlos"
de una manera mucho m치s sencilla, para ello mandamos a llamar a la funci칩n
=VGroup=:

#+begin_src python
  todo_junto = VGroup(triangulo, cuadrado, circulo, letra) # El orden importa!!!
  todo_junto.move_to(ORIGIN) # 쯋na traslaci칩n?
  self.add(todo_junto)
#+end_src

Para cerrar dejo el contenido completo del archivo (dibujando la letra):

#+begin_src python
  from manim import *

  class HolaMundo(Scene):
      def construct(self):
          self.camera.background_color = "#ece6e2"

          verde = "#87c2a5"
          azul  = "#525893"
          rojo  = "#e07a5f"
          negro = "#343434" # Los dise침adores dicen que es "malo" usar el negro puro

          circulo = Circle(color=azul, fill_opacity=1).shift(LEFT)
          cuadrado = Square(color=rojo, fill_opacity=1).shift(UP)
          triangulo = Triangle(color=verde, fill_opacity=1).shift(RIGHT)

          letra = MathTex(r"\mathbb{J}", fill_color=negro).scale(6)
          letra.shift(3 * LEFT + 1.5 * UP)

          todo_junto = VGroup(triangulo, cuadrado, circulo, letra) # El orden importa!!!
          todo_junto.move_to(ORIGIN) # 쯋na traslaci칩n?
          self.add(todo_junto)

          # Recuerda renderizar esto ejecutando lo siguiente en la l칤nea de comandos:
          # manim hola_mundo.py
#+end_src


** Crear anotaciones

Para dibujar un punto se hace uso del m칠todo =Dot=, para dibujar una l칤nea usamos
=Line=, en ocasiones queremos decorar un elemento que fue declarado con
anterioridad (puede que ese elemento sea el resultado de una transformaci칩n),
uno de los tantos m칠todos para decorar es =set_color=.

#+begin_src python
  from manim import *

  class Anotaciones(Scene):
      def construct(self):
          punto = Dot([-2, -1, 0]) # Creamos un punto en un plano
          punto2 = Dot([2, 1, 0])  # Creamos otro punto

          # Con base en los puntos definidos anteriormente creamos una l칤nea
          linea = Line(punto.get_center(), punto2.get_center()).set_color(ORANGE)

          # Si renderizamos esto obtendr칤amos una l칤nea anaranjada
          #self.add(linea, punto, punto2)

          llave1 = Brace(linea) # Decoramos la l칤nea con una llave
          texto_llave1 = llave1.get_text("Distancia horizontal")

          # Decoramos la l칤nea con otra llave
          # Pero esta vez le decimos que la direcci칩n de la misma ser치 rotada "pi"
          # Y sacamos el vector unitario.
          llave2 = Brace(linea, direction=linea.copy().rotate(PI).get_unit_vector())
          texto_llave2 = llave2.get_text("Distancia vertical")

          llave3 = Brace(linea, direction=linea.copy().rotate(PI / 2).get_unit_vector())
          texto_llave3 = llave2.get_text("$x - x_1$")

          self.add(linea, punto, punto2, llave1, llave2, llave3, texto_llave1, texto_llave2, texto_llave3)
#+end_src

** Dibujando un vector en un plano

Para dibujar un plano hacemos uso del m칠todo =NumberPlane=, mientras que, para
dibujar un vector necesitamos llamar =Arrow=

#+begin_src python
  from manim import *

  class CajaDeVectores(Scene):
      def construct(self):
          punto = Dot(ORIGIN) # Dibujamos un punto en el origen
          # Los vectores pueden son de tres dimensiones
          vector = Arrow(ORIGIN, [2, 2, 0], buff=0) # Dibujamos el vector (2,2, 0)
          plano = NumberPlane() # Dibujamos un plano
          texto_origen = Text('(0, 0)').next_to(dot, DOWN)
          texto_punta_vector = Text('(2, 2)').next_to(arrow.get_end(), RIGHT)
          self.add(plano, punto, vector, texto_origen, texto_punta_vector)
#+end_src

** Generando un gradiente

Podemos generar un objeto animable desde una imagen con =ImageMobject=:

#+begin_src python
  from manim import *

  class Gradiente(Scene):
      def construct(self):
          n = 256 # Queremos n칰meros entre 0 y 255
          arreglo = np.uint8(
              [[i * 256 / n for i in range(0, n)] for _ in range(0, n)]
          )
          # arreglo.shape # => (256, 256)
          imagen = ImageMobject(arreglo).scale(2)
          imagen.background_rectangle = SurroundingRectangle(imagen, GREEN)
          self.add(imagen, imagen.background_rectangle)
#+end_src

** Animaciones

Las animaciones hacen uso de la funci칩n =play=, como en el Power Point podemos
"animar" las transiciones con la funci칩n =FadeIn= para que se vea "bonito".

#+begin_src python
  from manim import *

  class BooleanOperations(Scene):
      def construct(self):
          ellipse1 = Ellipse(
              width=4.0, height=5.0, fill_opacity=0.5, color=BLUE, stroke_width=10
          ).move_to(LEFT)
          ellipse2 = ellipse1.copy().set_color(color=RED).move_to(RIGHT)
          bool_ops_text = MarkupText("<u>Operaciones Booleanas</u>").next_to(ellipse1, UP * 3)
          ellipse_group = Group(bool_ops_text, ellipse1, ellipse2).move_to(LEFT * 3)
          self.play(FadeIn(ellipse_group))

          i = Intersection(ellipse1, ellipse2, color=GREEN, fill_opacity=0.5)
          self.play(i.animate.scale(0.25).move_to(RIGHT * 5 + UP * 2.5))
          intersection_text = Text("Intersecci칩n", font_size=23).next_to(i, UP)
          self.play(FadeIn(intersection_text))

          u = Union(ellipse1, ellipse2, color=ORANGE, fill_opacity=0.5)
          union_text = Text("Uni칩n", font_size=23)
          self.play(u.animate.scale(0.3).next_to(i, DOWN, buff=union_text.height * 3))
          union_text.next_to(u, UP)
          self.play(FadeIn(union_text))

          e = Exclusion(ellipse1, ellipse2, color=YELLOW, fill_opacity=0.5)
          exclusion_text = Text("Diferencia Sim칠trica", font_size=23)
          self.play(e.animate.scale(0.3).next_to(u, DOWN, buff=exclusion_text.height * 3.5))
          exclusion_text.next_to(e, UP)
          self.play(FadeIn(exclusion_text))

          d = Difference(ellipse1, ellipse2, color=PINK, fill_opacity=0.5)
          difference_text = Text("Diferencia", font_size=23)
          self.play(d.animate.scale(0.3).next_to(u, LEFT, buff=difference_text.height * 3.5))
          difference_text.next_to(d, UP)
          self.play(FadeIn(difference_text))
#+end_src


** Usando una figura como gu칤a para una animaci칩n

Podemos utilizar referencias geom칠tricas para aplicar m치s animaciones, como
ejemplo est치n las funciones =GrowFromCenter=, =Transform=, =MoveAlongPath= y =Rotating=.

#+begin_src python
  from manim import *

  class PointMovingOnShapes(Scene):
      def construct(self):
          circle = Circle(radius=1, color=BLUE)
          dot = Dot()
          dot2 = dot.copy().shift(RIGHT)
          self.add(dot)

          line = Line([3, 0, 0], [5, 0, 0])
          self.add(line)

          self.play(GrowFromCenter(circle))
          self.play(Transform(dot, dot2))
          self.play(MoveAlongPath(dot, circle), run_time=2, rate_func=linear)
          self.play(Rotating(dot, about_point=[2, 0, 0]), run_time=1.5)
          self.wait()
#+end_src

Podemos escalar y rotar objetos:

#+begin_src python
  from manim import *

  class MovingAround(Scene):
      def construct(self):
          square = Square(color=BLUE, fill_opacity=1)
          circle = Circle(color=BLUE, fill_opacity=0.8)

          self.play(square.animate.shift(LEFT))
          self.play(square.animate.set_fill(PINK))
          self.play(square.animate.scale(0.3))
          self.play(square.animate.rotate(2.5))
          self.play(square.animate.shift(RIGHT))
          self.play(Transform(square, circle))
#+end_src

** Ejercicio

쮺칩mo har칤as la siguiente animaci칩n?

Ver el archivo =ejercicio1.mp4=

** Poner etiquetas mientras animamos

#+begin_src python
  from manim import *

  class MovingAngle(Scene):
      def construct(self):
          centro_rotacion = LEFT

          posicion_theta = ValueTracker(110)
          linea = Line(LEFT, RIGHT)
          linea_que_se_mueve = Line(LEFT, RIGHT)
          referencia = linea_que_se_mueve.copy()
          linea_que_se_mueve.rotate(
              posicion_theta.get_value() * DEGREES, about_point=centro_rotacion
          )
          a = Angle(linea, linea_que_se_mueve, radius=0.5, other_angle=False)
          tex = MathTex(r"\theta").move_to(
              Angle(
                  linea, linea_que_se_mueve, radius=0.5 + 3 * SMALL_BUFF, other_angle=False
              ).point_from_proportion(0.5)
          )

          self.add(linea, linea_que_se_mueve, a, tex)
          self.wait()

          linea_que_se_mueve.add_updater(
              lambda x: x.become(referencia.copy()).rotate(
                  posicion_theta.get_value() * DEGREES, about_point=centro_rotacion
              )
          )

          a.add_updater(
              lambda x: x.become(Angle(linea, linea_que_se_mueve, radius=0.5, other_angle=False))
          )
          tex.add_updater(
              lambda x: x.move_to(
                  Angle(
                      linea, linea_que_se_mueve, radius=0.5 + 3 * SMALL_BUFF, other_angle=False
                  ).point_from_proportion(0.5)
              )
          )

          self.play(posicion_theta.animate.set_value(40))
          self.play(posicion_theta.animate.increment_value(140))
          self.play(tex.animate.set_color(RED), run_time=0.5)
          self.play(posicion_theta.animate.set_value(300))
#+end_src

** Moviendo puntos

#+begin_src python
  from manim import *

  class MovingDots(Scene):
      def construct(self):
          d1,d2=Dot(color=BLUE),Dot(color=GREEN)
          dg=VGroup(d1,d2).arrange(RIGHT,buff=1)
          l1=Line(d1.get_center(),d2.get_center()).set_color(RED)
          x=ValueTracker(0)
          y=ValueTracker(0)
          d1.add_updater(lambda z: z.set_x(x.get_value()))
          d2.add_updater(lambda z: z.set_y(y.get_value()))
          l1.add_updater(lambda z: z.become(Line(d1.get_center(),d2.get_center())))
          self.add(d1,d2,l1)
          self.play(x.animate.set_value(5))
          self.play(y.animate.set_value(4))
          self.wait()
#+end_src

** Moviendo grupos de objetos

#+begin_src python
  from manim import *

  class MovingGroupToDestination(Scene):
      def construct(self):
          group = VGroup(Dot(LEFT), Dot(ORIGIN), Dot(RIGHT, color=RED), Dot(2 * RIGHT)).scale(1.4)
          dest = Dot([3, 3, 0], color=YELLOW)
          self.add(group, dest)
          self.play(group.animate.shift(dest.get_center() - group[2].get_center()))
          self.wait(0.6)
#+end_src

** Frame Box

En ocasiones presentamos texto y queremos enfocar la atenci칩n a una parte de
칠ste, para eso existe el frame box, para declararlo utilizamos la funci칩n
=SurroundingRectangle=, cuando escribimos ecuaciones es buena idea separar los
elementos de la misma para poder enfocar el frame box en un elemento:

 #+begin_src python
   from manim import *

   class MovingFrameBox(Scene):
       def construct(self):
           text=MathTex(
               "\\frac{d}{dx}f(x)g(x)=",
               "f(x)\\frac{d}{dx}g(x)",
               "+",
               "g(x)\\frac{d}{dx}f(x)",
           )
           titulo = Text("Derivada de una multiplicaci칩n").next_to(text, UP, buff = 1)
           self.play(Write(titulo))
           self.play(Write(text))
           framebox1 = SurroundingRectangle(text[1], buff = .1)
           framebox2 = SurroundingRectangle(text[3], buff = .1)
           framebox3 = SurroundingRectangle(text, buff = .3)
           self.play(
               Create(framebox1),
           )
           self.wait()
           self.play(
               ReplacementTransform(framebox1,framebox2),
           )
           self.wait()
           self.play(
               ReplacementTransform(framebox2, framebox3),
           )
           self.wait()
 #+end_src


Tambi칠n podemos hacer zoom a partes de la ecuaci칩n:

#+begin_src python
  class ZoomCamara(MovingCameraScene):
      def construct(self):
          equation = MathTex("4x^2-8x+1", "=", "2*(2x-1)^2")

          self.add(equation)
          self.play(self.camera.frame.animate.move_to(equation[0]).set(width=equation[0].width*2))
          self.wait(0.3)
          self.play(self.camera.frame.animate.move_to(equation[2]).set(width=equation[2].width*2))
#+end_src

** Seguir un trazo con un punto

#+begin_src python
  from manim import *

  class PointWithTrace(Scene):
      def construct(self):
          path = VMobject()
          dot = Dot()
          path.set_points_as_corners([dot.get_center(), dot.get_center()])

          def update_path(path):
              previous_path = path.copy()
              previous_path.add_points_as_corners([dot.get_center()])
              path.become(previous_path)

          path.add_updater(update_path)
          self.add(path, dot)
          self.play(Rotating(dot, radians=PI, about_point=RIGHT, run_time=2))
          self.wait()
          self.play(dot.animate.shift(UP))
          self.play(dot.animate.shift(LEFT))
          self.wait()
#+end_src

** Graficando con Manim

Manim puede ser utilizado para generar gr치ficas:

#+begin_src python
  from manim import *


  class CreateGraph(Scene):
      def construct(self):
          axes = Axes(
              x_range=[-3, 3],
              y_range=[-5, 5],
              axis_config={"color": BLUE},
          )

          # Create Graph
          graph = axes.plot(lambda x: x**2, color=WHITE)
          graph_label = axes.get_graph_label(graph, label='x^{2}')

          graph2 = axes.plot(lambda x: x**3, color=WHITE)
          graph_label2 = axes.get_graph_label(graph2, label='x^{3}')

          # Display graph
          self.play(Create(axes), Create(graph), Write(graph_label))
          self.wait(1)
          self.play(Transform(graph, graph2), Transform(graph_label, graph_label2))
          self.wait(1)
#+end_src

#+begin_src python
  from manim import *

  class SinAndCosFunctionPlot(Scene):
      def construct(self):
          axes = Axes(
              x_range=[-10, 10.3, 1],
              y_range=[-1.5, 1.5, 1],
              x_length=10,
              axis_config={"color": GREEN},
              x_axis_config={
                  "numbers_to_include": np.arange(-10, 10.01, 2),
                  "numbers_with_elongated_ticks": np.arange(-10, 10.01, 2),
              },
              tips=False,
          )
          axes_labels = axes.get_axis_labels()
          sin_graph = axes.plot(lambda x: np.sin(x), color=BLUE)
          cos_graph = axes.plot(lambda x: np.cos(x), color=RED)

          sin_label = axes.get_graph_label(
              sin_graph, "\\sin(x)", x_val=-10, direction=UP / 2
          )
          cos_label = axes.get_graph_label(cos_graph, label="\\cos(x)")

          vert_line = axes.get_vertical_line(
              axes.i2gp(TAU, cos_graph), color=YELLOW, line_func=Line
          )
          line_label = axes.get_graph_label(
              cos_graph, "x=2\pi", x_val=TAU, direction=UR, color=WHITE
          )

          plot = VGroup(axes, sin_graph, cos_graph, vert_line)
          labels = VGroup(axes_labels, sin_label, cos_label, line_label)
          self.add(plot, labels)
#+end_src

Para graficar en 3D nuestra escena debe heredar de =TheeDScene=:

#+begin_src python
  from manim import *

  class threeDGraph(ThreeDScene):
      def construct(self):
          axes = ThreeDAxes()
          circle=Circle()
          self.set_camera_orientation(phi=75 * DEGREES, theta=30 * DEGREES)
          text3d = Text("Texto en 3D")
          self.add(circle,axes)
          self.add_fixed_in_frame_mobjects(text3d)
          text3d.to_corner(UL)
          self.add(axes)
          self.wait()
#+end_src

** Uso con numpy

Podemos hacer uso de la funci칩n =numpy.argmin= para encontrar el valor m칤nimo de
una matriz:

#+begin_src python
  from manim import *

  class ArgMinExample(Scene):
      def construct(self):
          ax = Axes(
              x_range=[0, 10], y_range=[0, 100, 10], axis_config={"include_tip": False}
          )
          labels = ax.get_axis_labels(x_label="x", y_label="f(x)")

          t = ValueTracker(0)

          def func(x):
              return 2 * (x - 5) ** 2
          graph = ax.plot(func, color=MAROON)

          initial_point = [ax.coords_to_point(t.get_value(), func(t.get_value()))]
          dot = Dot(point=initial_point)

          # c2p es una abreviaci칩n de la funci칩n coords_to_point()
          dot.add_updater(lambda x: x.move_to(ax.c2p(t.get_value(), func(t.get_value()))))
          x_space = np.linspace(*ax.x_range[:2],200)
          minimum_index = func(x_space).argmin()

          self.add(ax, labels, graph, dot)
          self.play(t.animate.set_value(x_space[minimum_index]))
          self.wait()
#+end_src

** Dibujando 치reas bajo la curva

#+begin_src python
  from manim import *

  class GraphAreaPlot(Scene):
      def construct(self):
          ax = Axes(
              x_range=[0, 5],
              y_range=[0, 6],
              x_axis_config={"numbers_to_include": [2, 3]},
              tips=False,
          )

          labels = ax.get_axis_labels()

          curve_1 = ax.plot(lambda x: 4 * x - x ** 2, x_range=[0, 4], color=BLUE_C)
          curve_2 = ax.plot(
              lambda x: 0.8 * x ** 2 - 3 * x + 4,
              x_range=[0, 4],
              color=GREEN_B,
          )

          line_1 = ax.get_vertical_line(ax.input_to_graph_point(2, curve_1), color=YELLOW)
          line_2 = ax.get_vertical_line(ax.i2gp(3, curve_1), color=YELLOW)

          riemann_area = ax.get_riemann_rectangles(curve_1, x_range=[0.3, 0.6], dx=0.03, color=BLUE, fill_opacity=0.5)
          area = ax.get_area(curve_2, [2, 3], bounded_graph=curve_1, color=GREY, opacity=0.5)

          self.add(ax, labels, curve_1, curve_2, line_1, line_2, riemann_area, area)
#+end_src

El 치rea bajo la curva no debe de ser est치tico:

#+begin_src python
  from manim import *

  class PolygonOnAxes(Scene):
      def get_rectangle_corners(self, bottom_left, top_right):
          return [
              (top_right[0], top_right[1]),
              (bottom_left[0], top_right[1]),
              (bottom_left[0], bottom_left[1]),
              (top_right[0], bottom_left[1]),
          ]

      def construct(self):
          ax = Axes(
              x_range=[0, 10],
              y_range=[0, 10],
              x_length=6,
              y_length=6,
              axis_config={"include_tip": False},
          )

          t = ValueTracker(5)
          k = 25

          graph = ax.plot(
              lambda x: k / x,
              color=YELLOW_D,
              x_range=[k / 10, 10.0, 0.01],
              use_smoothing=False,
          )

          def get_rectangle():
              polygon = Polygon(
                  ,*[
                      ax.c2p(*i)
                      for i in self.get_rectangle_corners(
                          (0, 0), (t.get_value(), k / t.get_value())
                      )
                  ]
              )
              polygon.stroke_width = 1
              polygon.set_fill(BLUE, opacity=0.5)
              polygon.set_stroke(YELLOW_B)
              return polygon

          polygon = always_redraw(get_rectangle)

          dot = Dot()
          dot.add_updater(lambda x: x.move_to(ax.c2p(t.get_value(), k / t.get_value())))
          dot.set_z_index(10)

          self.add(ax, graph, dot)
          self.play(Create(polygon))
          self.play(t.animate.set_value(10))
          self.play(t.animate.set_value(k / 10))
          self.play(t.animate.set_value(5))
#+end_src


** Efectos de c치mara

#+begin_src python
  from manim import *

  class FollowingGraphCamera(MovingCameraScene):
      def construct(self):
          self.camera.frame.save_state()

          # create the axes and the curve
          ax = Axes(x_range=[-1, 10], y_range=[-1, 10])
          graph = ax.plot(lambda x: np.sin(x), color=BLUE, x_range=[0, 3 * PI])

          # create dots based on the graph
          moving_dot = Dot(ax.i2gp(graph.t_min, graph), color=ORANGE)
          dot_1 = Dot(ax.i2gp(graph.t_min, graph))
          dot_2 = Dot(ax.i2gp(graph.t_max, graph))

          self.add(ax, graph, dot_1, dot_2, moving_dot)
          self.play(self.camera.frame.animate.scale(0.5).move_to(moving_dot))

          def update_curve(mob):
              mob.move_to(moving_dot.get_center())

          self.camera.frame.add_updater(update_curve)
          self.play(MoveAlongPath(moving_dot, graph, rate_func=linear))
          self.camera.frame.remove_updater(update_curve)

          self.play(Restore(self.camera.frame))
#+end_src

#+begin_src python
  from manim import *

  class MovingZoomedSceneAround(ZoomedScene):
  # contributed by TheoremofBeethoven, www.youtube.com/c/TheoremofBeethoven
      def __init__(self, **kwargs):
          ZoomedScene.__init__(
              self,
              zoom_factor=0.3,
              zoomed_display_height=1,
              zoomed_display_width=6,
              image_frame_stroke_width=20,
              zoomed_camera_config={
                  "default_frame_stroke_width": 3,
                  },
              ,**kwargs
          )

      def construct(self):
          dot = Dot().shift(UL * 2)
          image = ImageMobject(np.uint8([[0, 100, 30, 200],
                                         [255, 0, 5, 33]]))
          image.height = 7
          frame_text = Text("Frame", color=PURPLE, font_size=67)
          zoomed_camera_text = Text("Zoomed camera", color=RED, font_size=67)

          self.add(image, dot)
          zoomed_camera = self.zoomed_camera
          zoomed_display = self.zoomed_display
          frame = zoomed_camera.frame
          zoomed_display_frame = zoomed_display.display_frame

          frame.move_to(dot)
          frame.set_color(PURPLE)
          zoomed_display_frame.set_color(RED)
          zoomed_display.shift(DOWN)

          zd_rect = BackgroundRectangle(zoomed_display, fill_opacity=0, buff=MED_SMALL_BUFF)
          self.add_foreground_mobject(zd_rect)

          unfold_camera = UpdateFromFunc(zd_rect, lambda rect: rect.replace(zoomed_display))

          frame_text.next_to(frame, DOWN)

          self.play(Create(frame), FadeIn(frame_text, shift=UP))
          self.activate_zooming()

          self.play(self.get_zoomed_display_pop_out_animation(), unfold_camera)
          zoomed_camera_text.next_to(zoomed_display_frame, DOWN)
          self.play(FadeIn(zoomed_camera_text, shift=UP))
          # Scale in        x   y  z
          scale_factor = [0.5, 1.5, 0]
          self.play(
              frame.animate.scale(scale_factor),
              zoomed_display.animate.scale(scale_factor),
              FadeOut(zoomed_camera_text),
              FadeOut(frame_text)
          )
          self.wait()
          self.play(ScaleInPlace(zoomed_display, 2))
          self.wait()
          self.play(frame.animate.shift(2.5 * DOWN))
          self.wait()
          self.play(self.get_zoomed_display_pop_out_animation(), unfold_camera, rate_func=lambda t: smooth(1 - t))
          self.play(Uncreate(zoomed_display_frame), FadeOut(frame))
          self.wait()
#+end_src

** Animaci칩n "avanzada"

#+begin_src python
  from manim import *

  class OpeningManim(Scene):
      def construct(self):
          title = Tex(r"Texto escrito en \LaTeX")
          basel = MathTex(r"\sum_{n=1}^\infty \frac{1}{n^2} = \frac{\pi^2}{6}")
          VGroup(title, basel).arrange(DOWN)
          self.play(
              Write(title),
              FadeIn(basel, shift=DOWN),
          )
          self.wait()

          transform_title = Tex("Transformaci칩n")
          transform_title.to_corner(UP + LEFT)
          self.play(
              Transform(title, transform_title),
              LaggedStart(*[FadeOut(obj, shift=DOWN) for obj in basel]),
          )
          self.wait()

          grid = NumberPlane()
          grid_title = Tex("Creando una malla", font_size=72)
          grid_title.move_to(transform_title)

          self.add(grid, grid_title)  # Make sure title is on top of grid
          self.play(
              FadeOut(title),
              FadeIn(grid_title, shift=UP),
              Create(grid, run_time=3, lag_ratio=0.1),
          )
          self.wait()

          grid_transform_title = Tex(
              r"Aplicando una transoframci칩n no lineal \\ a la malla"
          )
          grid_transform_title.move_to(grid_title, UL)
          grid.prepare_for_nonlinear_transform()
          self.play(
              grid.animate.apply_function(
                  lambda p: p
                            + np.array(
                      [
                          np.sin(p[1]),
                          np.sin(p[0]),
                          0,
                      ]
                  )
              ),
              run_time=3,
          )
          self.wait()
          self.play(Transform(grid_title, grid_transform_title))
          self.wait()
#+end_src

#+begin_src python
  from manim import *

  class SineCurveUnitCircle(Scene):
      # contributed by heejin_park, https://infograph.tistory.com/230
      def construct(self):
          self.show_axis()
          self.show_circle()
          self.move_dot_and_draw_curve()
          self.wait()

      def show_axis(self):
          x_start = np.array([-6,0,0])
          x_end = np.array([6,0,0])

          y_start = np.array([-4,-2,0])
          y_end = np.array([-4,2,0])

          x_axis = Line(x_start, x_end)
          y_axis = Line(y_start, y_end)

          self.add(x_axis, y_axis)
          self.add_x_labels()

          self.origin_point = np.array([-4,0,0])
          self.curve_start = np.array([-3,0,0])

      def add_x_labels(self):
          x_labels = [
              MathTex("\pi"), MathTex("2 \pi"),
              MathTex("3 \pi"), MathTex("4 \pi"),
          ]

          for i in range(len(x_labels)):
              x_labels[i].next_to(np.array([-1 + 2*i, 0, 0]), DOWN)
              self.add(x_labels[i])

      def show_circle(self):
          circle = Circle(radius=1)
          circle.move_to(self.origin_point)
          self.add(circle)
          self.circle = circle

      def move_dot_and_draw_curve(self):
          orbit = self.circle
          origin_point = self.origin_point

          dot = Dot(radius=0.08, color=YELLOW)
          dot.move_to(orbit.point_from_proportion(0))
          self.t_offset = 0
          rate = 0.25

          def go_around_circle(mob, dt):
              self.t_offset += (dt * rate)
              # print(self.t_offset)
              mob.move_to(orbit.point_from_proportion(self.t_offset % 1))

          def get_line_to_circle():
              return Line(origin_point, dot.get_center(), color=BLUE)

          def get_line_to_curve():
              x = self.curve_start[0] + self.t_offset * 4
              y = dot.get_center()[1]
              return Line(dot.get_center(), np.array([x,y,0]), color=YELLOW_A, stroke_width=2 )


          self.curve = VGroup()
          self.curve.add(Line(self.curve_start,self.curve_start))
          def get_curve():
              last_line = self.curve[-1]
              x = self.curve_start[0] + self.t_offset * 4
              y = dot.get_center()[1]
              new_line = Line(last_line.get_end(),np.array([x,y,0]), color=YELLOW_D)
              self.curve.add(new_line)

              return self.curve

          dot.add_updater(go_around_circle)

          origin_to_circle_line = always_redraw(get_line_to_circle)
          dot_to_curve_line = always_redraw(get_line_to_curve)
          sine_curve_line = always_redraw(get_curve)

          self.add(dot)
          self.add(orbit, origin_to_circle_line, dot_to_curve_line, sine_curve_line)
          self.wait(8.5)

          dot.remove_updater(go_around_circle)
#+end_src

** Ejemplos

- Animaci칩n de encontrar m칤nimo en [[https://colab.research.google.com/drive/1QTVHgyXXEXkLNydGm2RiD56XB1b4uflp?usp=sharing][Google Colab]]
- Tutorial de Manim en [[https://www.youtube.com/watch?v=rUsUrbWb2D4][youtube]].
- C칩digo fuente de todos los v칤deos de 3blue1brown en [[https://github.com/3b1b/videos/tree/master][github]].
